# Generated by Django 4.2.4 on 2023-08-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsRental', '0002_alter_car_consumption_alter_car_car_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cars_type',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Shooting brake', 'Shooting brake'), ('Suv', 'Suv'), ('Kombi', 'Kombi'), ('Van', 'Van'), ('Coupe', 'Coupe'), ('Sedan', 'Sedan')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(choices=[('RWD', 'Tylni'), ('FWD', 'Przedni'), ('AWD', '4x4')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Hybrid', 'Hybryda'), ('Electric', 'Elektryczny'), ('Petrol', 'Benzyna')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='no_gears',
            field=models.CharField(choices=[('5', '5'), ('7', '7'), ('6', '6'), ('8', '8')], max_length=8),
        ),
    ]
