# Generated by Django 4.2.4 on 2023-08-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsRental', '0003_alter_car_cars_type_alter_car_drive_alter_car_engine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='media/avatars/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='cars_type',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Kombi', 'Kombi'), ('Van', 'Van'), ('Suv', 'Suv'), ('Shooting brake', 'Shooting brake'), ('Sedan', 'Sedan')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(choices=[('AWD', '4x4'), ('RWD', 'Tylni'), ('FWD', 'Przedni')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Electric', 'Elektryczny'), ('Hybrid', 'Hybryda'), ('Petrol', 'Benzyna')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='no_gears',
            field=models.CharField(choices=[('5', '5'), ('6', '6'), ('8', '8'), ('7', '7')], max_length=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatyczna'), ('Manual', 'Manualna')], max_length=32),
        ),
    ]
