# Generated by Django 4.2.4 on 2023-08-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsRental', '0004_car_avatar_alter_car_cars_type_alter_car_drive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cars_type',
            field=models.CharField(choices=[('Van', 'Van'), ('Suv', 'Suv'), ('Shooting brake', 'Shooting brake'), ('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Kombi', 'Kombi')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(choices=[('RWD', 'Tylni'), ('FWD', 'Przedni'), ('AWD', '4x4')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Electric', 'Elektryczny'), ('Diesel', 'Diesel'), ('Petrol', 'Benzyna'), ('Hybrid', 'Hybryda')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='no_gears',
            field=models.CharField(choices=[('6', '6'), ('5', '5'), ('7', '7'), ('8', '8')], max_length=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manual', 'Manualna'), ('Automatic', 'Automatyczna')], max_length=32),
        ),
    ]
