# Generated by Django 4.2.4 on 2023-08-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsRental', '0005_alter_car_cars_type_alter_car_drive_alter_car_engine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cars_type',
            field=models.CharField(choices=[('Coupe', 'Coupe'), ('Hatchback', 'Hatchback'), ('Shooting brake', 'Shooting brake'), ('Suv', 'Suv'), ('Sedan', 'Sedan'), ('Van', 'Van'), ('Kombi', 'Kombi')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(choices=[('AWD', '4x4'), ('RWD', 'Tylni'), ('FWD', 'Przedni')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Elektryczny', 'Electric'), ('Benzyna', 'Petrol'), ('Hybryda', 'Hybrid'), ('Diesel', 'Diesel')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='no_gears',
            field=models.CharField(choices=[('8', '8'), ('7', '7'), ('5', '5'), ('6', '6')], max_length=8),
        ),
    ]
