# Generated by Django 4.2.4 on 2023-08-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsRental', '0006_alter_car_cars_type_alter_car_drive_alter_car_engine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Consumption',
            new_name='consumption',
        ),
        migrations.AlterField(
            model_name='car',
            name='cars_type',
            field=models.CharField(choices=[('Van', 'Van'), ('Sedan', 'Sedan'), ('Shooting brake', 'Shooting brake'), ('Kombi', 'Kombi'), ('Suv', 'Suv'), ('Coupe', 'Coupe'), ('Hatchback', 'Hatchback')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(choices=[('Przedni', 'Przedni'), ('4x4', '4x4'), ('Tylni', 'Tylni')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Benzyna', 'Benzyna'), ('Elektryczny', 'Elektryczny'), ('Hybryda', 'Hybryda')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='no_gears',
            field=models.CharField(choices=[('6', '6'), ('5', '5'), ('7', '7'), ('8', '8')], max_length=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatyczna', 'Automatyczna'), ('Manuala', 'Manualna')], max_length=32),
        ),
    ]
