# Generated by Django 4.2.4 on 2023-08-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsRental', '0007_rename_consumption_car_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='cars_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Shooting brake', 'Shooting brake'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Van', 'Van'), ('Kombi', 'Kombi'), ('Suv', 'Suv')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(choices=[('4x4', '4x4'), ('Tylni', 'Tylni'), ('Przedni', 'Przedni')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[('Benzyna', 'Benzyna'), ('Elektryczny', 'Elektryczny'), ('Hybryda', 'Hybryda'), ('Diesel', 'Diesel')], max_length=32),
        ),
        migrations.AlterField(
            model_name='car',
            name='no_gears',
            field=models.CharField(choices=[('5', '5'), ('7', '7'), ('8', '8'), ('6', '6')], max_length=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Manuala', 'Manualna'), ('Automatyczna', 'Automatyczna')], max_length=32),
        ),
    ]
